---
name: React to pull request
on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - name: Check using gitdm-sync
      run: |
        (curl -s "${{ secrets.SYNC_URL }}/pr/${GITHUB_REF}" |& tee output.txt | grep 'CHECK_OK') || ( cat output.txt; exit 1)
